vich_uploader:
    db_driver: orm
    mappings:
        expertise_images:
            uri_prefix: /images/actualite
            upload_destination: '%kernel.project_dir%/public/images/actualite'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
